/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginproyectop1b;

import javax.swing.JOptionPane;

/**
 *
 * @author crcg
 */
public class ModificarCurso extends javax.swing.JFrame {

    private Curso modificarCurso;
    
    /**
     * Creates new form ModificarCurso
     */
    public ModificarCurso(int posicion) {
        initComponents();
        
        modificarCurso = LoginProyectoP1B.cursos.get(posicion);// utiliza el constructor con la posicion seleccionada para ubicar el curso a modificar
       
         for(profesor e : LoginProyectoP1B.profesor){//con este for se llena el combobox de profesores con el nombre
            jComboBox1.addItem(e.getUsuario());
            }
         
        jTextField1.setText(String.valueOf(modificarCurso.getId()));// se setean cada uno de los datos del curso a modificar en los jTextField
        jTextField2.setText(modificarCurso.getNombre());
        jTextField3.setText(modificarCurso.getSeccion());
        FechaInicio.setText(modificarCurso.getFechainicio());
        FechaFin.setText(modificarCurso.getFechaFin());
        jTextField10.setText(modificarCurso.getHoraInicio());
        jTextField11.setText(modificarCurso.getHoraFin());
      
        jComboBox1.setSelectedItem(modificarCurso.Profesor);// esta linea coloca el combobox con el dato del profesor asignado al curso
        
        String ProfesorAnt = jComboBox1.getSelectedItem().toString() ;//agrego una variable string para el valor actual de profesor seleccionado en el combobox
        
        profesor profesorSeleccionado = null;// ingreso un profesor que almacenara el profesor seleccionado en el curso
        Curso cursoSeleccionado = null;//ingreso un curso que contendra el curso seleccionado actualmente
        
          for(profesor e : LoginProyectoP1B.profesor){//este for recorre el arraylist de profesores para ubicar el profesor actual del curso
            if(e.getNombre().equals(ProfesorAnt)){//en el if se compara el valor del nombre de los profesores y la variable ProfesorAnt
                profesorSeleccionado = e;//se ubica el profesor
                break;
            }        
        
       }
          for(Curso f : LoginProyectoP1B.cursos){ //este for ubica el curso que estamos modificando en el arraylist de cursos
              
               if(f.getNombre().equals(modificarCurso.getNombre())){//con este if se compara el nombre de modificarCurso con los cursos para ubicarlo
                cursoSeleccionado = f;//se ubica el curso
                break;
            } 
              
          }
            if(profesorSeleccionado!=null && cursoSeleccionado!=null){//si hay un curso y profesor ubicados entonces ejecute
            profesorSeleccionado.cursos.remove(cursoSeleccionado);//borramos el curso agregado  previamente al profesor para poder modificarlo
            cursoSeleccionado.profesor.remove(profesorSeleccionado);//borramos el profesor previamente asignado al curso para poder modificarlo
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FechaInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FechaFin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Creación de Cursos");

        jLabel1.setText("ID:");

        jTextField1.setEditable(false);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Sección:");

        jLabel5.setText("Fecha de inicio:");

        jLabel6.setText("Fecha Termina:");

        jLabel7.setText("Hora de Inicio:");

        jLabel8.setText("Hora Termina:");

        jLabel15.setText("ProfesorNuevo");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(86, 86, 86)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(57, 57, 57)
                                        .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(55, 55, 55)
                                .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15))
                    .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fechaInicio = FechaInicio.getText();
        String fechaFin = FechaFin.getText();//estas variables tienen los datos de los jTextField para agregarlos a los datos del curso 
        String profesor1 = jComboBox1.getSelectedItem().toString();//agregamos una variable que contendra el valor del profesor seleccionado el combobox
       
       

       
        modificarCurso.setId(Integer.parseInt(jTextField1.getText()));//se modifican todos los datos del curso con los datos actuales de los jTextField
        modificarCurso.setNombre(jTextField2.getText());
        modificarCurso.setSeccion(jTextField3.getText());
        modificarCurso.setFechainicio(fechaInicio);
        modificarCurso.setFechaFin(fechaFin);
        modificarCurso.setHoraInicio(jTextField10.getText());
        modificarCurso.setHoraFin(jTextField11.getText());
        modificarCurso.Profesor= jComboBox1.getSelectedItem().toString();//se agrega el nombre del profesor a la variable con el combobox
       
       

        profesor profesorSeleccionado = null;// se ingresa un profesor que contendra el nuevo profesor del curso
        Curso cursoSeleccionado = null; //se ingresa un curso que contendra el curso que fue actualizado
        
        for(profesor e : LoginProyectoP1B.profesor){// for que ubica el profesor con el dato del combobox
            if(e.getNombre().equals(profesor1)){
                profesorSeleccionado = e;
                
                break;
            }

        }
          for(Curso f : LoginProyectoP1B.cursos){//for que ubica el curso con el nombre del curso modificado
              
               if(f.getNombre().equals(modificarCurso.getNombre())){
                cursoSeleccionado = f;
                break;
            } 
              
          }
          
         if(profesorSeleccionado!=null && cursoSeleccionado!=null){// si el curso y profesor fue ubicado se procede a agregarlos ya que fue borrado previamente el profesor anterior
            profesorSeleccionado.cursos.add(cursoSeleccionado);//agregamos el curso modificado a el array de cursos del profesor
            cursoSeleccionado.profesor.add(profesorSeleccionado);//agregamos el profesor nuevo a el array de cursos
            JOptionPane.showMessageDialog(this, "curso Actualizado exitosamente");// mensaje que indica que todo fue realizado con exito
        }
      

 
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FechaFin;
    private javax.swing.JTextField FechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
