/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginproyectop1b;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crcg
 */
public class VerAlumnosPorCurso extends javax.swing.JFrame {

    private Curso cursoProfesor;
    public Curso tabla ;
    /**
     * Creates new form VerAlumnos
     */
    public VerAlumnosPorCurso(int posicion) {
        initComponents();
        cursoProfesor = LoginProyectoP1B.profesorLogeado.cursos.get(posicion);
        jLabel3.setText(cursoProfesor.getNombre() + " seccion " + cursoProfesor.getSeccion());
        
        for(Curso f : LoginProyectoP1B.cursos){ //este for ubica el curso que estamos modificando en el arraylist de cursos
              
               if(f.getNombre().equals(cursoProfesor.getNombre())){//con este if se compara el nombre de modificarCurso con los cursos para ubicarlo
                tabla = f;//se ubica el curso
                break;
            } 
              
          }
        llenarTabla();
                  
         
         
        
    }
    public void llenarTabla(){
        
       
         DefaultTableModel data = new DefaultTableModel(new String[]{"Carne","Nombre","Apellido","nota",},cursoProfesor.alumnos.size());
            jTable1.setModel(data);

            int row = 0;

            for(Alumno e : cursoProfesor.alumnos){
               
                jTable1.setValueAt(e.getCarne(), row, 0);
                jTable1.setValueAt(e.getNombre(), row, 1);
                jTable1.setValueAt(e.getApellido(), row, 2);
                jTable1.setValueAt(e.notas, row, 3);
                
                
                row ++;
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText(" Alumnos");

        jLabel3.setText("jLabel3");

        jButton2.setText("agregarNota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar 1 para agregar nota");

        jButton3.setText("notasPorAlumno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3)))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BienvenidaProfesor b = new BienvenidaProfesor();
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Alumno alumnoSinNota = new Alumno();
        Alumno alumnoConNota = new Alumno();
        Notas notaAlumno = new Notas();
        int seleccion = jTable1.getSelectedRow();
        String nombre ;
        String carne;
        String apellido;
        String password;
        
        notaAlumno.setNombre(cursoProfesor.getNombre());
        notaAlumno.setSeccion(cursoProfesor.getSeccion());
        notaAlumno.setId(cursoProfesor.getId());
        notaAlumno.setHoraInicio(cursoProfesor.getHoraInicio());
        notaAlumno.setHoraFin(cursoProfesor.getHoraFin());
        notaAlumno.setFechainicio(cursoProfesor.getFechainicio());
        notaAlumno.setFechaFin(cursoProfesor.getFechaFin());
        
        for(Alumno a : tabla.alumnos){
                 if(a.getCarne().equals(tabla.alumnos.get(seleccion))){
                     alumnoSinNota = a ;//si encuentra un alumno lo guarda en alumnoSinNota
                     break;                     
                     
             }
         }
        notaAlumno.alumnos.add(alumnoSinNota);
    
    //     tabla.alumnos.set(seleccion, alumnoConNota);
      //   nombre = alumnoSinNota.getNombre();
        // apellido = alumnoSinNota.getApellido();
         //carne = alumnoSinNota.getCarne();
        // password = alumnoSinNota.getPassword();
       // alumnoConNota.setCarne(carne);
       // alumnoConNota.setNombre(nombre);
       // alumnoConNota.setApellido(apellido);
       // alumnoConNota.setPassword(password);
      //  alumnoConNota.nota = jTextField1.getText();
      //  tabla.alumnos.set(seleccion, alumnoConNota).setNombre(nombre);
      // tabla.alumnos.set(seleccion, alumnoConNota).setApellido(apellido);
     //  tabla.alumnos.set(seleccion, alumnoConNota).setCarne(carne);
     //  tabla.alumnos.set(seleccion, alumnoConNota).setPassword(password);
       //tabla.alumnos.remove(alumnoSinNota);
        //cursoProfesor.alumnos.remove(alumnoSinNota);
        //cursoProfesor.alumnos.add(alumnoConNota);
        //tabla.alumnos.add(alumnoConNota);
      //      JOptionPane.showMessageDialog(this, "curso asignado exitosamente");
            llenarTabla();
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      int pos = jTable1.getSelectedRow();
      ModificarNotaAlumno1 a = new ModificarNotaAlumno1(cursoProfesor.alumnos.get(pos));
      a.setVisible(true);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
